import os
import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    linkedin_email = os.environ.get("LINKEDIN_EMAIL")
    linkedin_password = os.environ.get("LINKEDIN_PASSWORD")
    if not linkedin_email or not linkedin_password:
        raise RuntimeError("LINKEDIN_EMAIL and LINKEDIN_PASSWORD must be set.")

    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.linkedin.com/")
    page.get_by_role("link", name="Sign in", exact=True).click()
    page.get_by_role("textbox", name="Email or phone").click()
    page.get_by_role("textbox", name="Email or phone").fill(linkedin_email)
    page.get_by_role("textbox", name="Email or phone").press("Tab")
    page.get_by_role("textbox", name="Password").fill(linkedin_password)
    page.get_by_role("textbox", name="Password").press("Enter")
    page.get_by_role("button", name="Sign in", exact=True).click()
    page.get_by_role("link", name="Write an article on LinkedIn").click()
    page.get_by_role("button", name="Djay Pandya AI Morning Brief").click()
    page.get_by_role("radio", name="AI Morning Brief").click()
    page.get_by_label("Write here. You can also").click()
    page.get_by_label("Write here. You can also").click(button="right")
    page.goto("https://www.linkedin.com/article/edit/7434910799472766976/")
    page.get_by_text("# Wednesday, 04 March").click()
    page.get_by_text("# Wednesday, 04 March").click(modifiers=["Shift"])
    page.get_by_text("# Wednesday, 04 March").click(modifiers=["Shift"])
    page.get_by_text("# Wednesday, 04 March").click(modifiers=["Shift"])
    page.get_by_text("# Wednesday, 04 March").click()
    page.get_by_text("# Wednesday, 04 March").dblclick()
    page.get_by_text("# Wednesday, 04 March").click()
    page.get_by_text("# Wednesday, 04 March").click()
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowLeft")
    page.get_by_role("textbox", name="Article editor content").press("Shift+ArrowRight")
    page.get_by_role("textbox", name="Article editor content").press("ControlOrMeta+x")
    page.get_by_role("textbox", name="Article editor content").fill("# \n\nGoogle launches Gemini 3.1 Flash-Lite for cheaper, faster AI work\n\nGoogle said on Tuesday, March 3, 2026 that Gemini 3.1 Flash-Lite is now in preview for developers and businesses. The company says it is its fastest and cheapest Gemini 3 model so far, built for high-volume work like translation, moderation, dashboards, and simulations. This matters because lower-cost models can help more teams use AI in everyday products without spending as much money.\n\nOpenAI and Amazon expand their AI partnership\n\nOpenAI said on Thursday, February 27, 2026 that it is expanding its deal with Amazon and AWS. The companies said AWS will distribute OpenAI Frontier to AWS customers, OpenAI will use about 2 gigawatts of Trainium capacity, and Amazon will invest $50 billion in OpenAI. This matters because big AI firms are now tying model platforms, cloud tools, and chip supply together at a much larger scale.\n\nUS agencies are told to stop using Anthropic technology\n\nThe Associated Press reported on Friday, February 27, 2026 that the Trump administration ordered federal agencies to stop using Anthropic's AI after a dispute over military use and safety limits. Anthropic said it would not remove safeguards tied to mass surveillance and fully autonomous weapons. This matters because the fight shows how fast AI policy, defense work, and model safety are colliding.\n\nPerplexity says Samsung is putting its AI deeper into Galaxy phones\n\nPerplexity said on Thursday, February 26, 2026 that its APIs are now deeply integrated into Samsung Galaxy S26 phones. The company says its assistant can work with Samsung apps, help power Bixby search and reasoning, and act as an optional default search engine in Samsung Browser. This matters because it shows AI companies are moving beyond chatbots and into the core software of major consumer devices.\n\nGoogle rolls out a faster AI image model called Nano Banana 2\n\nGoogle said on Wednesday, February 26, 2026 that Nano Banana 2 is rolling out across products like Gemini, Search, and Ads. The company says the new model combines stronger image quality with faster editing and adds more support for content verification through SynthID and C2PA credentials. This matters because AI image tools are becoming easier to use at scale while pressure grows to label AI-made content clearly.\n\n\n")
    page.get_by_role("textbox", name="Title").click()
    page.get_by_role("textbox", name="Title").fill("Wednesday, 04 March 2026")
    page.get_by_text("#", exact=True).click()
    page.get_by_role("textbox", name="Article editor content").fill("\n\n\nGoogle launches Gemini 3.1 Flash-Lite for cheaper, faster AI work\n\nGoogle said on Tuesday, March 3, 2026 that Gemini 3.1 Flash-Lite is now in preview for developers and businesses. The company says it is its fastest and cheapest Gemini 3 model so far, built for high-volume work like translation, moderation, dashboards, and simulations. This matters because lower-cost models can help more teams use AI in everyday products without spending as much money.\n\nOpenAI and Amazon expand their AI partnership\n\nOpenAI said on Thursday, February 27, 2026 that it is expanding its deal with Amazon and AWS. The companies said AWS will distribute OpenAI Frontier to AWS customers, OpenAI will use about 2 gigawatts of Trainium capacity, and Amazon will invest $50 billion in OpenAI. This matters because big AI firms are now tying model platforms, cloud tools, and chip supply together at a much larger scale.\n\nUS agencies are told to stop using Anthropic technology\n\nThe Associated Press reported on Friday, February 27, 2026 that the Trump administration ordered federal agencies to stop using Anthropic's AI after a dispute over military use and safety limits. Anthropic said it would not remove safeguards tied to mass surveillance and fully autonomous weapons. This matters because the fight shows how fast AI policy, defense work, and model safety are colliding.\n\nPerplexity says Samsung is putting its AI deeper into Galaxy phones\n\nPerplexity said on Thursday, February 26, 2026 that its APIs are now deeply integrated into Samsung Galaxy S26 phones. The company says its assistant can work with Samsung apps, help power Bixby search and reasoning, and act as an optional default search engine in Samsung Browser. This matters because it shows AI companies are moving beyond chatbots and into the core software of major consumer devices.\n\nGoogle rolls out a faster AI image model called Nano Banana 2\n\nGoogle said on Wednesday, February 26, 2026 that Nano Banana 2 is rolling out across products like Gemini, Search, and Ads. The company says the new model combines stronger image quality with faster editing and adds more support for content verification through SynthID and C2PA credentials. This matters because AI image tools are becoming easier to use at scale while pressure grows to label AI-made content clearly.\n\n\n")
    page.get_by_role("button", name="Next").click()
    page.get_by_role("paragraph").click()
    page.locator(".ql-clipboard").fill("Big AI news this week includes Google's push to make models cheaper and faster, OpenAI's deeper tie-up with Amazon, a major US government clash with Anthropic, Perplexity moving further into Samsung phones, and Google's latest image model rollout. Together, these stories show that AI competition is now about cost, distribution, device access, infrastructure, and rules for safe use.\n\n\n#AI\n#TechNews\n#Innovation\n\n")
    page.get_by_role("button", name="Publish").click()
    page.get_by_role("button", name="Dismiss").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
